const routes = {
  home: '/',
  costumerDashboard: '/dashboard',
  aboutUs: '/aboutUs',
  contact: '/contact',
  testimonials: '/testimonials',
  faqs: '/faqs',
  termsService: '/termsService',
  foodGrid: '/foodGrid',
  blog: '/blog',
  blogDetails: '/blogDetails',
  login: '/login',
  cart: '/cart',
  chefs: '/chefs',
  reservation: '/reservation',
  register: '/register',
  privacyPolicy: '/privacyPolicy',
  foodGrip: '/foodGrip',
  foodDetails: '/foodDetails',
  cartView: '/cartView',
  checkout: '/checkout',
  orderSucces: '/orderSucces',
};

export default routes;
